-- AlterTable
ALTER TABLE `kpi_definitions` MODIFY `role` ENUM('SUPER_ADMIN', 'INSTALLER', 'DEVELOPER', 'DESIGNER', 'MACHINE_OPERATOR', 'LIAISON', 'ADMIN_STAFF', 'SALES_STAFF') NOT NULL;

-- AlterTable
ALTER TABLE `user_role_assignments` MODIFY `role` ENUM('SUPER_ADMIN', 'INSTALLER', 'DEVELOPER', 'DESIGNER', 'MACHINE_OPERATOR', 'LIAISON', 'ADMIN_STAFF', 'SALES_STAFF') NOT NULL;

-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('SUPER_ADMIN', 'INSTALLER', 'DEVELOPER', 'DESIGNER', 'MACHINE_OPERATOR', 'LIAISON', 'ADMIN_STAFF', 'SALES_STAFF') NOT NULL;
